### ISSUE TITLE
Support version pinning with Flakes

### ISSUE THREAD

**Issue by workflow** [workflow/nix-shell-action#196]

**Comment by otavio** [comment]
Any progress on this?

**Comment by workflow** [comment]
> Any progress on this?

If you have a use case in mind, happy to use that as test and implement.

**Comment by otavio** [comment]
I would love to use it with flakes and be able to call the commands without need to wrap them on `nix develop -c bash ...`.

**Comment by workflow** [comment]
Version `3.1.0` now supports [fully qualified flakes](https://github.com/workflow/nix-shell-action/pull/277), so you should be able to do this:

```
      - uses: workflow/nix-shell-action@v3
        with:
          flakes: .#hello,nixpkgs#docker
          script: |
            # Runs hello from a local flake.nix
            hello
            # Uses docker from the nixpkgs registry (see https://raw.githubusercontent.com/NixOS/flake-registry/master/flake-registry.json)
            command -v docker
```

...with a local flake.nix. You can also leave out the local flake input (`.#hello`) - if it's a default output of your flake, it should just be available.

Let me know if that solves your use case!
